language: node_js
node_js:
  - 5.6.0
services:
  - mongodb
notifications:
  slack: aehr:Onhz0k4eQcFbDbha4LgRTrnw
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
